// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5qJeYuRq-1GvCDrkOe7o-Ec3fSN6m7U',
    appId: '1:40780948560:web:e66ab852f50ed652a49d55',
    messagingSenderId: '40780948560',
    projectId: 'controle-vagas',
    authDomain: 'controle-vagas.firebaseapp.com',
    storageBucket: 'controle-vagas.firebasestorage.app',
    measurementId: 'G-RKVWSEEWB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4HNlddH_IXfex9HaUwJPtJ1F-NDGV2Y',
    appId: '1:40780948560:android:6aeacc0f860e5080a49d55',
    messagingSenderId: '40780948560',
    projectId: 'controle-vagas',
    storageBucket: 'controle-vagas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt47CC-Ft8R4FvmsphZ9Io5lgxYhBNPIg',
    appId: '1:40780948560:ios:02fb290e012235cea49d55',
    messagingSenderId: '40780948560',
    projectId: 'controle-vagas',
    storageBucket: 'controle-vagas.firebasestorage.app',
    iosBundleId: 'com.example.vagas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt47CC-Ft8R4FvmsphZ9Io5lgxYhBNPIg',
    appId: '1:40780948560:ios:02fb290e012235cea49d55',
    messagingSenderId: '40780948560',
    projectId: 'controle-vagas',
    storageBucket: 'controle-vagas.firebasestorage.app',
    iosBundleId: 'com.example.vagas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh5qJeYuRq-1GvCDrkOe7o-Ec3fSN6m7U',
    appId: '1:40780948560:web:811188b5b2fb0837a49d55',
    messagingSenderId: '40780948560',
    projectId: 'controle-vagas',
    authDomain: 'controle-vagas.firebaseapp.com',
    storageBucket: 'controle-vagas.firebasestorage.app',
    measurementId: 'G-J28THEXN0K',
  );

}